# Site settings
title: Sonic Screwdriver
email: tung@boltops.com
url: http://sonic-screwdriver.cloud
description: "Multi-functional tool to manage AWS infrastructure"
keywords: "AWS EC2 Container Service, AWS ECS, AWS EC2, ssh, debug, docker run, docker exec, productivity, tool"
skills: ""
meta_author: Tung Nguyen

# Google webmaster tools
google_verify:
google_analytics: UA-98684555-2

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 47a970
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  links: 3fda78

# Footer settings
footer:
  copyright: BoltOps, LLC
  location: San Francisco, CA
  social: BoltOps
  credits:
  contact: contact@boltops.com
  phone:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/boltopslabs
  - title: github
    url: http://github.com/boltopslabs

# Credits content
credits: 'BoltOps, LLC'

# Build settings
markdown: kramdown
permalink: pretty

gh_url: "https://github.com/boltopslabs/sonic"

collections:
  docs:
    name: "Documentation"
    output: true

defaults:
  - values:
      layout: default

plugins_dir:
 - jekyll-coffeescript
